export { default as TextMarqueeForm } from './TextMarqueeForm'
export { default as SliderForm } from './SliderForm'
export { default as BannerForm } from './BannerForm'
export { default as FooterBannerForm } from './FooterBannerForm'
export { default as ArticlesAdsForm } from './ArticlesAdsForm'
export { default as GeneralSettingForm } from './GeneralSettingForm'
export { default as LogoImagesForm } from './LogoImagesForm'
